server:
  port: 8081

logging:
  path: ./logs
  level:
    org.springframework.web: trace

spring:
  application:
    name: sofa-sb
  redis:
    database: 1
    port: 6379
    host: 127.0.0.1
    timeout: 5000
    lettuce:
      pool:
        max-active: 16
        max-idle: 5
  datasource:
    hikari:
      auto-commit: false
      minimum-idle: 5
      maximum-pool-size: 64
      pool-name: SpHikariCP
      connection-test-query: select 1
    url: jdbc:mysql://localhost:3307/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

