server:
  port: 8081

logging:
  path: ./logs
  level:
    org.springframework.web: trace

spring:
  application:
    name: sofa-sb
  redis:
    database: 1
    port: 6379
    host: 127.0.0.1
    timeout: 5000
    lettuce:
      pool:
        max-active: 16
        max-idle: 5
